### ISSUE TITLE
Cannot read property 'comment_system' of undefined

### ISSUE THREAD

**Issue by Arcuppi** [qutang/theme-cutie-demo#1]
Unhandled rejection TypeError: Cannot read property 'comment_system' of undefined
    at Object.eval [as tpl] (eval at precompile (/Users/Arcuppi/Documents/Hexo/blog/node_modules/swig-templates/lib/swig.js:497:13), <anonymous>:11:881)
    at compiled (/Users/Arcuppi/Documents/Hexo/blog/node_modules/swig-templates/lib/swig.js:618:18)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/Arcuppi/Documents/Hexo/blog/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/Arcuppi/Documents/Hexo/blog/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/Arcuppi/Documents/Hexo/blog/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at wrapper (/Users/Arcuppi/Documents/Hexo/blog/node_modules/lodash/lodash.js:4941:19)
    at Object.eval [as tpl] (eval at precompile (/Users/Arcuppi/Documents/Hexo/blog/node_modules/swig-templates/lib/swig.js:497:13), <anonymous>:6:119)
    at compiled (/Users/Arcuppi/Documents/Hexo/blog/node_modules/swig-templates/lib/swig.js:618:18)
---------------------------------------------------------------------------------------------------Hello! I encountered the above error when using cutie v1.0.1. Firstly ,I thought it was a missing step. So I reinstall it again. It's still the same error. When I installed cutie v2.0.6, it was normal. So why is this ? Please help me

**Comment by qutang** [comment]
Sorry about that. But the 'comment_system" variable is not officially supported in cutie v1.0.1, the code may have changed since then. Can you post your configuration file (_config.yml) and data file (source/data/cutie.yml) for me to debug?

Also, this demo site is probably out of date, I have not tested it against v2.x, so use it with caution.

**Comment by qutang** [comment]
Also, v1.0.1 is no longer maintained. I suggest you move to v2.x. If you have specific features you really like in v1.0.1, please post an issue and we can see if we can add them back.

**Comment by Arcuppi** [comment]
Well, I just prefer the v1.0.1 navigation bar. It doesn't matter. The
latest version is pretty good. I use the latest version. thank you！

2018-03-10 9:05 GMT+08:00 Qu Tang <notifications@github.com>:
